// Generated by scripts/generate-slideshow.mjs. Do not edit by hand.

export const slideshowImages = [
  {
    "src": "/slideshow/DuncanChair.jpg",
    "alt": "Duncan relaxing in an oversized red chair"
  },
  {
    "src": "/slideshow/EvanChair.jpg",
    "alt": "Evan relaxing in an oversized red chair at night"
  },
  {
    "src": "/slideshow/patioWide.jpg",
    "alt": "Night Soup playing an outdoor patio show under string lights"
  },
  {
    "src": "/slideshow/PXL_20260111_211829539.MP.jpg",
    "alt": "Night Soup rehearsing together"
  },
  {
    "src": "/slideshow/PXL_20260629_212501513.MP.jpg",
    "alt": "Duncan wearing a Night Soup shirt"
  }
] as const;
